image: collaborating.tuhh.de:5005/hoou-tuhh/projekte/quaxp-gruppe/jupyter-book-test:latest

build:
  script:
    - bundle install
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - "public/"
      

